
#ifndef SW_SYSTEM_ACTUATORS_CFG_H
#define SW_SYSTEM_ACTUATORS_CFG_H

//#define PLATFORM_ACTUATORS_MONITOR_PERIOD 1000
#define PLATFORM_ACTUATORS_PIN_MOTOR DINOUTS_PIN_6

#endif //SW_SYSTEM_ACTUATORS_CFG_H
