
#ifndef SW_SYSTEM_DINOUTS_CFG_H
#define SW_SYSTEM_DINOUTS_CFG_H

#define PLATFORM_DINOUTS_DEVICE_ID XPAR_AXI_GPIO_INOUTS_DEVICE_ID
//#define PLATFORM_DINOUTS_MONITOR_PERIOD 1000

#endif //SW_SYSTEM_DINOUTS_CFG_H
