
#ifndef SW_SYSTEM_IRPROXIMITY_CFG_H
#define SW_SYSTEM_IRPROXIMITY_CFG_H

#include <dinouts.h>

#define PLATFORM_IRPROXIMITY_MONITOR_PERIOD 1000
#define PLATFORM_IRPROXIMITY_PIN_POWER_SUPPLY DINOUTS_PIN_5
#define PLATFORM_IRPROXIMITY_ADC XADC_CHANNEL_1
#define PLATFORM_IRPROXIMITY_THREASHOLD 3500
//#define PLATFORM_IRPROXIMITY_TURN_OFF

#endif //SW_SYSTEM_IRPROXIMITY_CFG_H
