
#ifndef SW_SYSTEM_IRPROXIMITY_CFG_H
#define SW_SYSTEM_IRPROXIMITY_CFG_H

#include <dinouts.h>

#define PLATFORM_IRPROXIMITY_MONITOR_PERIOD 1000
#define PLATFORM_IRPROXIMITY_UPDATE_PERIOD 10
#define PLATFORM_IRPROXIMITY_AVERAGING 16
#define PLATFORM_IRPROXIMITY_ENABLE_RX DINOUTS_PIN_5
#define PLATFORM_IRPROXIMITY_ENABLE_TX DINOUTS_PIN_6
#define PLATFORM_IRPROXIMITY_ADC XADC_CHANNEL_0
#define PLATFORM_IRPROXIMITY_THREASHOLD 100

#endif //SW_SYSTEM_IRPROXIMITY_CFG_H
