
#ifndef SW_SYSTEM_LEDS_CONFIG_H
#define SW_SYSTEM_LEDS_CONFIG_H

#define PLATFORM_LEDS_MONITOR_PERIOD 1000

#define PLATFORM_LEDS_GPIO_1 XPAR_AXI_GPIO_0_DEVICE_ID
#define PLATFORM_LEDS_GPIO_2 XPAR_AXI_GPIO_1_DEVICE_ID

#endif //SW_SYSTEM_LEDS_CONFIG_H
