//
// Created by vaxi on 5/2/17.
//

#ifndef SW_SYSTEM_SUPERCAP_CFG_H
#define SW_SYSTEM_SUPERCAP_CFG_H

#include "xadc_cfg.h"

#define PLATFORM_SUPERCAP_INPUT             XADC_CHANNEL_1
#define PLATFORM_SUPERCAP_UPDATE_PERIOD     1000
//#define PLATFORM_SUPERCAP_MONITOR_PERIOD    1000
#define PLATFORM_SUPERCAP_VOLTAGE_SCALE     2
#define PLATFORM_SUPERCAP_VOLTAGE_MAX       5000
#define PLATFORM_SUPERCAP_THREASHOLD_GREEN  50
#define PLATFORM_SUPERCAP_THREASHOLD_BLUE   70
#define PLATFORM_SUPERCAP_LED_TIMEOUT       50

#endif //SW_SYSTEM_SUPERCAP_CFG_H
