
#ifndef SW_SYSTEM_XADC_CFG_H
#define SW_SYSTEM_XADC_CFG_H

/* Comment next line for disabling ADC monitor */
//#define PLATFORM_XADC_MONITOR_INPUT_PERIOD 1000

#define PLATFORM_XADC_ANALOG_SWITCH_0 DINOUTS_PIN_UNKNOWN
#define PLATFORM_XADC_ANALOG_SWITCH_1 DINOUTS_PIN_7
#define PLATFORM_XADC_ANALOG_SWITCH_2 DINOUTS_PIN_8
#define PLATFORM_XADC_ANALOG_SWITCH_3 DINOUTS_PIN_9


#endif //SW_SYSTEM_XADC_CFG_H
